spring:
  profiles: local
  datasource:
      url: jdbc:mysql://192.168.136.100:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
logging:
  config: classpath:logback-local.xml
